name: Roman's Chiro
favicon: null
layout_spectrum: 0.50632
typography_spectrum: 0.5693137780763209
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#384843'
    - '#587b68'
    - '#accab7'
  brandStrength: 0.11262779613025486
  lightness: 0.5
  saturation: 0.7241652398370206
  rhythmicContrast: 0.46632643486373127
purpose: []
